name: mlops
channels:
  - conda-forge
dependencies:
  - scikit-learn==0.21.2
  - pytest==4.5.0
  - numpy==1.16.4
  - pandas==0.24.2
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - scipy==1.3.0
    - hypothesis==4.24.0
    - sklearn-pandas
    - azure-cli==2.0.65
    - flask
    - dill 
    - requests
    